---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-gen-deployment
  labels:
    app: quote-gen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quote-gen
  template:
    metadata:
      labels:
        app: quote-gen
    spec:
      containers:
        - name: quote-gen
          image: gksingl/quote-generator
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: quote-gen-service
  labels:
    app: quote-gen
    svc: test-quote-gen
spec:
  type: NodePort
  selector:
    app: quote-gen
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30012
